version: '3'

services:
  nchan:
    build:
      context: .
      dockerfile: Dockerfile
    image: nchan
    command:
    - nginx
    - "-g"
    - "daemon off;"
    ports:
    - "8080:80"
    volumes:
    - ./conf.d:/etc/nginx/conf.d/
    - ./sites-enabled:/etc/nginx/sites-enabled/
